### PR TITLE
Introduce a new map provider API which enables not to know maps at compile-time

### PR DESCRIPTION
**Pull request by qnga**
Related to #182.

This new API will enable to develop a plugin letting users select maps of interest from a built-in repository, and even provide their own WMTS URLs.

### CODE REVIEW

**Comment by qnga** [comment]
Hello,
Do you plan to review this PR? I've got my plugin basically ready for publishing. It wouldn't make much sense if it's not compatible with a published Trekarta build though.

**Comment by StrikeLines** [comment]
We are also very interested in using this PR to view WMTS. Any plans to merge it with production?

**Comment by andreynovikov** [comment]
If you are still interested, I will work on that.

**Comment by qnga** [comment]
I am still interested!

**Comment by andreynovikov** [comment]
Ok, can you fix conflicts as I've made many changes to `MainActivity.java` since that. And can you also explain what you mean by "not to know maps at compile-time"? This is about plugin compilation, yes?

**Comment by andreynovikov** [comment]
Also I would prefer if you will rewrite current providers instead of introducing new ones. As all current plugins are written by me: https://github.com/andreynovikov/trekarta-online-maps I would rather update them to conform with new API.

**Comment by andreynovikov** [comment]
May be you also have any idea on [this](https://github.com/andreynovikov/trekarta/blob/d9732d1561d28f01ef6c2a5f28b5c45854bdfa1d/app/src/main/java/mobi/maptrek/maps/MapIndex.java#L140)?

**Comment by qnga** [comment]
> And can you also explain what you mean by "not to know maps at compile-time"? This is about plugin compilation, yes?

Yes, with my API, maps are not necessarily known when you compile the plugin app. That enables plugin apps to let users choose maps they are interested in and provide service keys for them.



I'll update the PR soon.

**Comment by qnga** [comment]
Done. I merged master and removed the old map provider API.

As to tile expiration, I guess we could use HTP cache-control headers. I don't think that would be related with plugins though, as they provide URLs for tiles rather than doing any request themselves.

**Pull request merged**
